const {
  PORT,
  PAGE_NUMBER,
  PAGE_SIZE,

  JWT_SECRET_KEY,

  DATABASE_HOST,
  DATABASE_PORT,
  DATABASE_NAME,
  DATABASE_USERNAME,
  DATABASE_PASSWORD,

  NOTIFICATION_MAIL_FROM,
  NOTIFICATION_MAIL_USERNAME,
  NOTIFICATION_MAIL_PASSWORD,

  VERIFICATION_CODE_EXPIRATION_TIME,
  WRONG_PASS_LIMIT,
  WRONG_PASS_LOCK_TIME,
} = process.env;

module.exports = {
  PORT: PORT || 80,
  PAGE_NUMBER_DEFAULT: parseInt(PAGE_NUMBER || 1, 10),
  PAGE_SIZE_DEFAULT: parseInt(PAGE_SIZE || 10, 10),

  JWT_SECRET_KEY,

  DATABASE_HOST,
  DATABASE_PORT,
  DATABASE_NAME,
  DATABASE_USERNAME,
  DATABASE_PASSWORD,

  NOTIFICATION_MAIL_FROM: NOTIFICATION_MAIL_FROM || 'admin@vaccinate.com',
  NOTIFICATION_MAIL_USERNAME,
  NOTIFICATION_MAIL_PASSWORD,

  VERIFICATION_CODE_EXPIRATION_TIME: parseInt(VERIFICATION_CODE_EXPIRATION_TIME || '300', 10), // unit: second

  WRONG_PASS_LIMIT: parseInt(WRONG_PASS_LIMIT || '5', 10),
  WRONG_PASS_LOCK_TIME: parseInt(WRONG_PASS_LOCK_TIME || '60', 10), // unit: second
};
